---
- name: Wait for automatic system updates to complete
  shell: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do echo "Waiting for apt lock..."; sleep 10; done
  become: yes
  timeout: 300

- name: Update system packages
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600
  become: yes
  retries: 3
  delay: 10

- name: Install essential packages
  apt:
    name:
      - curl
      - wget
      - git
      - unzip
      - jq
      - htop
      - tree
      - nano
      - python3-pip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - net-tools
      - netcat
    state: present
  become: yes

- name: Install Python packages
  pip:
    name:
      - docker
      - docker-compose
    state: present
  become: yes

- name: Create project directory
  file:
    path: "/home/ubuntu/unmute"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  become: yes
