all:
  children:
    aws_gpu_instances:
      hosts:
        unmute-gpu:
          ansible_host: "{{ lookup('env', 'UNMUTE_SERVER_IP') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env', 'ANSIBLE_PRIVATE_KEY_FILE') | default('~/unmute_key') }}"
          ansible_python_interpreter: /usr/bin/python3
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          
      vars:
        github_repo: "{{ lookup('env', 'GITHUB_REPO') | default('micpostyam/cvcrafted_unmute') }}"
        mistral_api_key: "{{ lookup('env', 'MISTRAL_API_KEY') }}"
        hugging_face_token: "{{ lookup('env', 'HUGGING_FACE_TOKEN') }}"
