---
- name: Clone Unmute repository
  git:
    repo: "https://github.com/micpostyam/cvcrafted_unmute.git"
    dest: "/home/ubuntu/unmute"
    clone: yes
    update: yes
    force: yes
  become_user: ubuntu

- name: Create environment file
  template:
    src: env.j2
    dest: "/home/ubuntu/unmute/.env"
    owner: ubuntu
    group: ubuntu
    mode: '0600'

- name: Create production docker-compose file
  template:
    src: docker-compose.production.yml.j2
    dest: "/home/ubuntu/unmute/docker-compose.production.yml"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Stop existing containers (if any)
  shell: |
    cd /home/ubuntu/unmute
    sudo docker-compose -f docker-compose.production.yml down || true
  become_user: ubuntu
  ignore_errors: yes

- name: Build Docker images
  shell: |
    cd /home/ubuntu/unmute
    sudo docker-compose -f docker-compose.production.yml build
  become_user: ubuntu
  register: build_result

- name: Start Unmute services
  shell: |
    cd /home/ubuntu/unmute
    sudo docker-compose -f docker-compose.production.yml up -d
  become_user: ubuntu
  register: start_result

- name: Wait for frontend service
  wait_for:
    port: 3000
    host: localhost
    timeout: 300
  ignore_errors: yes

- name: Wait for backend service
  wait_for:
    port: 8000
    host: localhost
    timeout: 300
  ignore_errors: yes

- name: Display container status
  shell: |
    cd /home/ubuntu/unmute
    sudo docker-compose -f docker-compose.production.yml ps
  become_user: ubuntu
  register: container_status

- name: Show container status
  debug:
    msg: "{{ container_status.stdout_lines }}"
