---
- name: Clone Unmute repository
  git:
    repo: "https://github.com/{{ github_repo }}.git"
    dest: "{{ project_directory }}"
    clone: yes
    update: yes
    force: yes
  become_user: "{{ project_user }}"

- name: Create environment file
  template:
    src: env.j2
    dest: "{{ project_directory }}/.env"
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: '0600'

- name: Create production docker-compose file
  template:
    src: docker-compose.production.yml.j2
    dest: "{{ project_directory }}/docker-compose.production.yml"
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: '0644'

- name: Stop existing containers (if any)
  shell: |
    cd {{ project_directory }}
    docker-compose -f docker-compose.production.yml down || true
  become_user: "{{ project_user }}"
  ignore_errors: yes

- name: Build Docker images
  shell: |
    cd {{ project_directory }}
    docker-compose -f docker-compose.production.yml build
  become_user: "{{ project_user }}"
  register: build_result

- name: Start Unmute services
  shell: |
    cd {{ project_directory }}
    docker-compose -f docker-compose.production.yml up -d
  become_user: "{{ project_user }}"
  register: start_result

- name: Wait for services to be ready
  wait_for:
    port: "{{ item }}"
    host: "{{ ansible_host }}"
    timeout: "{{ service_startup_timeout }}"
  loop:
    - "{{ unmute_frontend_port }}"
    - "{{ unmute_backend_port }}"
  ignore_errors: yes

- name: Create monitoring script
  template:
    src: monitor.sh.j2
    dest: "{{ project_directory }}/monitor.sh"
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    mode: '0755'

- name: Create auto-shutdown script
  template:
    src: auto-shutdown.sh.j2
    dest: /usr/local/bin/unmute-auto-shutdown.sh
    mode: '0755'
  become: yes
  when: enable_auto_shutdown

- name: Setup auto-shutdown cron job
  cron:
    name: "Unmute auto-shutdown"
    minute: "{{ shutdown_time.split(':')[1] }}"
    hour: "{{ shutdown_time.split(':')[0] }}"
    job: "/usr/local/bin/unmute-auto-shutdown.sh"
  become: yes
  when: enable_auto_shutdown

- name: Display container status
  shell: |
    cd {{ project_directory }}
    docker-compose -f docker-compose.production.yml ps
  become_user: "{{ project_user }}"
  register: container_status

- name: Show container status
  debug:
    msg: "{{ container_status.stdout_lines }}"
