---
- name: configure nvidia runtime
  shell: nvidia-ctk runtime configure --runtime=docker
  become: yes

- name: restart docker
  systemd:
    name: docker
    state: restarted
  become: yes

- name: reboot server
  reboot:
    reboot_timeout: 300
    pre_reboot_delay: 10
    post_reboot_delay: 30
  become: yes
  when: ansible_reboot_pending is defined
